# Shelltone configuration. This file is safe to source from Bash and Zsh.
SHELLTONE_THEME=afterglow
. "$SHELLTONE_ROOT/themes/$SHELLTONE_THEME.sh"
SHELLTONE_TWO_LINES=true
SHELLTONE_ADD_NEWLINE=true
SHELLTONE_SHOW_TIME=true
SHELLTONE_TIME_FORMAT='%I:%M:%S %p'
SHELLTONE_SHOW_CONTEXT=auto
SHELLTONE_SHOW_VENV=true
SHELLTONE_ALIAS_PACK=starter
