# Strongly divided blocks that remain readable in an ordinary Unicode font.
SHELLTONE_PROMPT_STYLE=blocks
SHELLTONE_SHOW_BAR=true
SHELLTONE_LEFT_DIVIDER='│'
SHELLTONE_RIGHT_DIVIDER='│'
SHELLTONE_LEFT_FADE=''
SHELLTONE_RIGHT_FADE=''
SHELLTONE_TOP_PREFIX='╭─'
SHELLTONE_INPUT_PREFIX='╰─'
SHELLTONE_PROMPT_SYMBOL='❯'
