# Framed two-line prompt with a subtle continuous bar.
SHELLTONE_PROMPT_STYLE=frame
SHELLTONE_SHOW_BAR=true
SHELLTONE_LAYOUT_BAR_CONTROLS=true
SHELLTONE_LAYOUT_DETAIL_CONTROLS=true
SHELLTONE_LEFT_DIVIDER='>'
SHELLTONE_RIGHT_DIVIDER='·'
SHELLTONE_LEFT_FADE='▓▒░'
SHELLTONE_RIGHT_FADE='░▒▓'
SHELLTONE_TOP_PREFIX='╭─'
SHELLTONE_INPUT_PREFIX='╰─'
SHELLTONE_PROMPT_SYMBOL='>'
