# A quiet, text-first look with no shaded bar or ornamental framing.
SHELLTONE_PROMPT_STYLE=pure
SHELLTONE_SHOW_BAR=false
SHELLTONE_LAYOUT_BAR_CONTROLS=false
SHELLTONE_LAYOUT_DETAIL_CONTROLS=false
SHELLTONE_GIT_DETAIL=false
SHELLTONE_PATH_MODE=full
SHELLTONE_VI_MODE=true
SHELLTONE_DURATION_THRESHOLD=5
SHELLTONE_SHOW_GIT_ICON=false
SHELLTONE_LEFT_DIVIDER=' '
SHELLTONE_RIGHT_DIVIDER=' · '
SHELLTONE_LEFT_FADE=''
SHELLTONE_RIGHT_FADE=''
SHELLTONE_TOP_PREFIX=''
SHELLTONE_INPUT_PREFIX=''
SHELLTONE_PROMPT_SYMBOL='❯'
