# Sparse one-line-friendly look with restrained separators.
SHELLTONE_PROMPT_STYLE=zen
SHELLTONE_SHOW_BAR=false
SHELLTONE_LAYOUT_BAR_CONTROLS=false
SHELLTONE_LAYOUT_DETAIL_CONTROLS=false
SHELLTONE_GIT_DETAIL=true
SHELLTONE_PATH_MODE=basename
SHELLTONE_VI_MODE=false
SHELLTONE_DURATION_THRESHOLD=5
SHELLTONE_LEFT_DIVIDER='  '
SHELLTONE_RIGHT_DIVIDER='  '
SHELLTONE_LEFT_FADE=''
SHELLTONE_RIGHT_FADE=''
SHELLTONE_TOP_PREFIX=''
SHELLTONE_INPUT_PREFIX=''
SHELLTONE_PROMPT_SYMBOL='❯'
