name: Checks

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Zsh checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
      - name: Install Zsh
        run: sudo apt-get update && sudo apt-get install --yes zsh
      - name: Run checks
        run: zsh ./tests/check.zsh
